# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Zwollander
tagline:          Bodybuilding & programming
url:              http://zwollander.github.io
paginate:         1
baseurl:          /
author:
  name:           Salva Alcántara
  url:            https://twitter.com/zwollander
  email:          zwollander@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/zwollander/zwollander.github.io
